Yemek Sitesi/lotusyemek/Controllers/CorbaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using lotusyemek.Models;

namespace lotusyemek.Controllers
{
    public class CorbaController : Controller
    {
        private lotusEntities db = new lotusEntities();

        // GET: Corba
        public ActionResult Index()
        {
            ViewBag.Sayi = db.TblMesajs.Count();
            ViewBag.Mesaj = db.TblMesajs.OrderByDescending(x => x.ID).ToList();
            return View(db.TblYemek1.OrderByDescending(x => x.ID).ToList());
        }


        // GET: Corba/Create
        public ActionResult Create()
        {
            ViewBag.Sayi = db.TblMesajs.Count();
            ViewBag.Mesaj = db.TblMesajs.OrderByDescending(x => x.ID).ToList();
            return View();
        }

        // POST: Corba/Create
        // Aşırı gönderim saldırılarından korunmak için bağlamak istediğiniz belirli özellikleri etkinleştirin. 
        // Daha fazla bilgi için bkz. https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ad,resim,aciklama")] TblYemek1 tblYemek1, HttpPostedFileBase resim)
        {
            if (ModelState.IsValid)
            {
                if (resim != null) // buradan logonun dolu olup olmadığını kontrol ediyoruz
                {

                    WebImage img = new WebImage(resim.InputStream); //bu ikisi resim ekleme
                    FileInfo imginfo = new FileInfo(resim.FileName);

                    string logoname = Guid.NewGuid().ToString() + imginfo.Extension; //resim adlandırma
                    img.Resize(1000, 1000);  // resim boyutu
                    img.Save("~/Uploads/Corba/" + logoname);
                    tblYemek1.resim = "/Uploads/Corba/" + logoname;


                }
                db.TblYemek1.Add(tblYemek1);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblYemek1);
        }

        // GET: Corba/Edit/5
        public ActionResult Edit(short? id)
        {
            ViewBag.Sayi = db.TblMesajs.Count();
            ViewBag.Mesaj = db.TblMesajs.OrderByDescending(x => x.ID).ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblYemek1 tblYemek1 = db.TblYemek1.Find(id);
            if (tblYemek1 == null)
            {
                return HttpNotFound();
            }
            return View(tblYemek1);
        }

        // POST: Corba/Edit/5
        // Aşırı gönderim saldırılarından korunmak için bağlamak istediğiniz belirli özellikleri etkinleştirin. 
        // Daha fazla bilgi için bkz. https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ad,resim,aciklama")] TblYemek1 tblYemek1, HttpPostedFileBase resim, int id)
        {
            if (ModelState.IsValid)
            {
                var s = db.TblYemek1.Where(x => x.ID == id).SingleOrDefault();
                if (resim != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(s.resim))) //daha önce kaydettiğimiz dosya varsa silme kodu
                    {
                        System.IO.File.Delete(Server.MapPath(s.resim));
                    }


                    WebImage img = new WebImage(resim.InputStream); //bu ikisi resim ekleme
                    FileInfo imginfo = new FileInfo(resim.FileName);

                    string logoname = Guid.NewGuid().ToString() + imginfo.Extension; //resim adlandırma
                    img.Resize(1000, 1000);  // resim boyutu
                    img.Save("~/Uploads/Corba/" + logoname);
                    s.resim = "/Uploads/Corba/" + logoname;
                }
                s.ad = tblYemek1.ad;
                s.aciklama = tblYemek1.aciklama;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblYemek1);
        }

        // GET: Corba/Delete/5
        public ActionResult Delete(short? id)
        {
            ViewBag.Sayi = db.TblMesajs.Count();
            ViewBag.Mesaj = db.TblMesajs.OrderByDescending(x => x.ID).ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblYemek1 tblYemek1 = db.TblYemek1.Find(id);
            if (tblYemek1 == null)
            {
                return HttpNotFound();
            }
            return View(tblYemek1);
        }

        // POST: Corba/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(short id)
        {
            TblYemek1 tblYemek1 = db.TblYemek1.Find(id);
            if (System.IO.File.Exists(Server.MapPath(tblYemek1.resim))) //daha önce kaydettiğimiz dosya varsa silme kodu
            {
                System.IO.File.Delete(Server.MapPath(tblYemek1.resim));
            }
            db.TblYemek1.Remove(tblYemek1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            ViewBag.Sayi = db.TblMesajs.Count();
            ViewBag.Mesaj = db.TblMesajs.OrderByDescending(x => x.ID).ToList();
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Yemek Sitesi/lotusyemek/Views/Corba/Create.cshtml
@model lotusyemek.Models.TblYemek1

@{
    ViewBag.Title = "Çorba Ekleme";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("Create", "Corba", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Çorba Ekle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Çorba Adı
            <div class="col-md-10">
                @Html.EditorFor(model => model.ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           Çorba Resim (Örnek 610x610 boy en eşit olacak)
            <div class="col-md-10">
                <input type="file" accept=".jpg,.png,.jpeg" name="resim" class="form-control" id="resim" />
            </div>
        </div>

        <div class="form-group">
          Açıklama
            <div class="col-md-10">
                @Html.EditorFor(model => model.aciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.aciklama, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div class="mt-3">
    @Html.ActionLink("Geri Dön", "Index")
</div>

Yemek Sitesi/lotusyemek/Views/Corba/Delete.cshtml
@model lotusyemek.Models.TblYemek1

@{
    ViewBag.Title = "Çorba Sil";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>Silmek İstediğinize Emin Misiniz?</h3>
<br />
<div>
    <h4>Çorba Sil</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Ad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ad)
        </dd>
        <dt>
            Açıklama
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aciklama)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color mt-3">
            <input type="submit" value="Sil" class="btn btn-danger" /> |
            @Html.ActionLink("Geri Dön", "Index")
        </div>
    }
</div>

Yemek Sitesi/lotusyemek/Views/Corba/Details.cshtml
@model lotusyemek.Models.TblYemek1

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TblYemek1</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.resim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.resim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aciklama)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Yemek Sitesi/lotusyemek/Views/Corba/Edit.cshtml
@model lotusyemek.Models.TblYemek1

@{
    ViewBag.Title = "Çorba Düzenle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



@using (Html.BeginForm("Edit", "Corba", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4> Çorba Düzenle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            Ad
            <div class="col-md-10">
                @Html.EditorFor(model => model.ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Resim
            <div class="col-md-10">
                <input type="file" accept=".jpg,.png,.jpeg" name="resim" class="form-control" id="resim" />
            </div>
        </div>

        <div class="form-group">
            Açıklama
            <div class="col-md-10">
                @Html.EditorFor(model => model.aciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.aciklama, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Güncelle" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div class="mt-3">
    @Html.ActionLink("Geri Dön", "Index")
</div>

Yemek Sitesi/lotusyemek/Views/Corba/Index.cshtml
@model IEnumerable<lotusyemek.Models.TblYemek1>

@{
    ViewBag.Title = "Çorbalar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Çorbalar</h2>

<p>
    <a href="/Corba/Create" class="btn btn-outline-success">Ekle</a>
</p>
<table class="table table-striped table-hover datatable">
    <thead>
        <tr>
            <th>
                Çorba Adı
            </th>
            <th>
                Resim
            </th>
            <th>
                Açıklama
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ad)
                </td>
                <td>
                    <img src="@item.resim" width="50" height="50" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.aciklama)
                </td>
                <td>
                    @Html.ActionLink("Düzenle", "Edit", new { id = item.ID, }, new { @class = "btn btn-warning" }) |
                    @Html.ActionLink("Sil", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>